### PR TITLE
Cope with URL escaped characters in iRODS paths through seamless authn

### LINKED ISSUE #137: Access to files with names containing URL function - propagating escaping through authn
We cannot currently access file in iRODS where there is a `#` somewhere in the path  [seamlessly through a ~authentication~ redirect process].
We need to be able to do that by substituting `#` with `%23` in the URL.
[edit](at the moment entering an escaped string in the URL results in a page returned with it unescaped - a different meaning to that of the original request).
[edit] i.e. using `/api/v1/irods/<some path with %23 for #>` works, but `/<some path with %23 for #>` fails.

We need to rethink where the unescaping is done, and/or the logic for it - perhaps...

### PR DESCRIPTION
**Pull request by dkj**
All gpt-5-codex medium thinking code.
Fixes #137

### CODE REVIEW

File: server/handlers.go [hunk 1]
```diff
@@ -317,14 +321,22 @@ func HandleIRODSGet(server *SqyrrlServer) http.Handler {
...
+		decodedPath, err := url.PathUnescape(r.URL.Path)
+		if err != nil {
+			corrLogger.Err(err).
+				Str("path", r.URL.Path).
+				Msg("Failed to decode request path")
+			writeErrorResponse(corrLogger, w, http.StatusBadRequest)
+			return
+		}
+
 		// The path should be clean as it has passed through the ServeMux, but since we're
```
Comment (dkj) [inline server/handlers.go:333]: Is this truly "clean" now following the new `decodedPath, err := url.PathUnescape(r.URL.Path)`
